name: Sync Files to KiKHanbot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出当前仓库的代码
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      # 克隆目标仓库到一个临时文件夹
      - name: Clone Target Repo to Temp Directory
        run: git clone https://${{ secrets.PUSH_TO_KIKHANBOT }}@github.com/WizisCool/KiKHanbot.git /tmp/tmpKiKHanbot

      # 复制文件到目标仓库的指定文件夹，同时排除不需要的文件和文件夹
      - name: Rsync Files
        run: |
          rsync -av --progress --exclude '.github/' --exclude 'Readme.md' --exclude '.git/' ./ /tmp/tmpKiKHanbot/HanbotConfig/
          # Note: The trailing slashes on the source and destination paths are important.

      # 提交和推送更改到目标仓库
      - name: Commit and Push
        run: |
          cd /tmp/tmpKiKHanbot
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          # 检查是否有任何更改
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sync changes from HanbotConfig repository"
            git push origin HEAD:master
          else
            echo "No changes to commit"
          fi
