name: Sync to KiKHanbot Repository's HanbotConfig Folder

on: 
  push:
  workflow_dispatch:

jobs:
  sync_to_kikhanbot:
    runs-on: ubuntu-latest

    steps:
      # 使用 Turnstyle 确保在同一时间只有一个此工作流实例在执行
      - name: Wait for other instances of this workflow
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 检出当前的代码
      - name: Checkout HanbotConfig Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取完整的 Git 历史

      # 配置 Git 信息
      - name: Set Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 推送代码到 KiKHanbot 仓库的 HanbotConfig 文件夹
      - name: Push to KiKHanbot Repository's HanbotConfig Folder
        run: |
          git clone https://github.com/WizisCool/KiKHanbot.git tmpKiKHanbot
          rsync -av --progress . tmpKiKHanbot/HanbotConfig/ --exclude tmpKiKHanbot/
          cd tmpKiKHanbot
          git add HanbotConfig/
          git commit -m "Sync changes from HanbotConfig repository"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_KIKHANBOT }} 
